apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: counter-backend
  name: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: '3000'

      labels:
        app: counter-backend
    spec:
      containers:
      - name: counter-backend
        image: registry.tino.sh/counter-app
        volumeMounts:
        - name: db-file
          mountPath: /opt
        env:
          - name: DBFILE
            valueFrom:
              configMapKeyRef:
                name: counter-config
                key: DBFILE
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 20
          failureThreshold: 2
      volumes:
      - name: db-file
        persistentVolumeClaim:
          claimName: pvc-db-file
